version: "3"
volumes:
  pgdata:
services:
  api: &api
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/api
    depends_on: 
      - db
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    command: python manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
