# Generated by Django 4.0.1 on 2022-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('domain', models.CharField(max_length=64)),
                ('requests_number', models.IntegerField()),
            ],
        ),
    ]
